# Generated by Django 5.0.3 on 2024-03-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('image', models.ImageField(upload_to='images/')),
                ('rating', models.PositiveIntegerField()),
                ('description', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
